CREATE SCHEMA commandbardb;
USE commandbardb;

create table funcionarios(
FUNC_ID INT PRIMARY KEY AUTO_INCREMENT,
FUNC_NAME VARCHAR(30) NOT NULL,
FUNC_SNAME VARCHAR(30) NOT NULL,
FUNC_CPF VARCHAR(20) NOT NULL,
FUNC_PASS VARCHAR(100) NOT NULL,
FUNC_CARG VARCHAR(100) NOT NULL,
FUNC_EMAIL VARCHAR(100) NOT NULL,
FUNC_SAL DOUBLE NOT NULL,
FUNC_ADMDATE DATE NOT NULL,
FUNC_DMSDATE DATE NULL,
FUNC_END VARCHAR(100) NOT NULL,
FUNC_NUM VARCHAR(30) NOT NULL,
FUNC_CEP VARCHAR(10) NOT NULL,
FUNC_CITY VARCHAR(60) NOT NULL,
FUNC_DISTRIC VARCHAR(60) NOT NULL,
FUNC_UF VARCHAR(2) NOT NULL,
FUNC_TOKEN VARCHAR(100) NULL
);

create table produtos(
PROD_ID INT PRIMARY KEY AUTO_INCREMENT,
PROD_DESC VARCHAR(60) NOT NULL,
PROD_QTD INT NOT NULL,
PROD_VALOR DOUBLE NOT NULL,
PROD_TIPO VARCHAR(60) NOT NULL,
PROD_STAT VARCHAR(11) NOT NULL,
PROD_MARCA VARCHAR(20) NOT NULL,
PROD_CATEG VARCHAR(60) NOT NULL
);


select * from funcionarios;

INSERT INTO FUNCIONARIOS (FUNC_NAME, FUNC_SNAME, FUNC_CPF, FUNC_PASS,FUNC_CARG, FUNC_EMAIL, FUNC_SAL, FUNC_ADMDATE, FUNC_END, FUNC_NUM, FUNC_CEP, FUNC_CITY,
FUNC_DISTRIC, FUNC_UF)  VALUES ('administrador','adm',11111111111,'$2y$10$1LaWiNz3mhJylVqLqICAuugfWBcF05vZPrYAULD07sUTE8xR0OuBm','gerente','adm@adm.com.br',1000.00,'2000-01-01','rua1','01',
'72016180','taguatinga','taguatinga','df' ) ;

SELECT FUNC_ID, FUNC_NAME, FUNC_CARG, FUNC_CPF, FUNC_EMAIL FROM FUNCIONARIOS;