CREATE SCHEMA commandbardb;
USE commandbardb;

create table funcionarios(
FUNC_ID INT PRIMARY KEY AUTO_INCREMENT,
FUNC_NAME VARCHAR(30) NOT NULL,
FUNC_SNAME VARCHAR(30) NOT NULL,
FUNC_CPF VARCHAR(20) NOT NULL,
FUNC_PASS VARCHAR(100) NOT NULL,
FUNC_CARG VARCHAR(100) NOT NULL,
FUNC_EMAIL VARCHAR(100) NOT NULL,
FUNC_SAL DOUBLE NOT NULL,
FUNC_ADMDATE DATE NOT NULL,
FUNC_DMSDATE DATE NULL,
FUNC_END VARCHAR(100) NOT NULL,
FUNC_NUM VARCHAR(30) NOT NULL,
FUNC_CEP VARCHAR(10) NOT NULL,
FUNC_CITY VARCHAR(60) NOT NULL,
FUNC_DISTRIC VARCHAR(60) NOT NULL,
FUNC_UF VARCHAR(2) NOT NULL,
FUNC_TOKEN VARCHAR(100) NOT NULL
);