CREATE SCHEMA commandbardb;
USE commandbardb;


CREATE TABLE ENDERECOS (
END_ID INT PRIMARY KEY AUTO_INCREMENT,
END_LOGR VARCHAR(100),
END_NUM VARCHAR(30),
END_CEP VARCHAR(10),
END_CITY VARCHAR(60),
END_DISTRIC VARCHAR(60),
END_UF CHAR(3)
);

CREATE TABLE PRODUTOS (
PROD_STAT VARCHAR(11),
PROD_VALOR DOUBLE,
PROD_QTD INT,
PROD_MARCA VARCHAR(20),
PROD_CATEG VARCHAR(60),
PROD_DESC VARCHAR(60),
PROD_ID INT PRIMARY KEY
);

CREATE TABLE FUNCIONARIOS (
FUNC_ID INT PRIMARY KEY AUTO_INCREMENT,
FUNC_ADMDATE DATE,
FUNC_DMSDATE DATE,
FUNC_EMAIL VARCHAR(100),
FUNC_TOKEN VARCHAR(100),
FUNC_NAME VARCHAR(30),
FUNC_SNAME VARCHAR(60),
FUNC_PASS VARCHAR(100),
FUNC_CARG VARCHAR(30),
FUNC_SAL DOUBLE,
FUNC_CPF VARCHAR(20),
END_ID INT,
CONSTRAINT FK_ENDFUN FOREIGN KEY(END_ID) REFERENCES ENDERECOS (END_ID)
);

CREATE TABLE FORNECEDORES (
FOR_ID INT PRIMARY KEY,
FOR_RAZAO VARCHAR(100),
FOR_DDD VARCHAR(4),
FOR_TEL VARCHAR(12),
FOR_CNPJ VARCHAR(20),
END_ID INT,
CONSTRAINT FK_ENDFOR FOREIGN KEY(END_ID) REFERENCES ENDERECOS (END_ID)
);

CREATE TABLE ALMOXARIFADOS (
EST_ID INT PRIMARY KEY,
QT_FORNECIDA INT,
DT_ENTRADA DATE,
FOR_ID INT,
PROD_ID INT,
CONSTRAINT FK_PRODALM FOREIGN KEY(PROD_ID) REFERENCES PRODUTOS (PROD_ID),
CONSTRAINT FK_FORALM FOREIGN KEY(FOR_ID) REFERENCES FORNECEDORES (FOR_ID)
);



CREATE TABLE COMANDAS (
COM_ID INT PRIMARY KEY,
COM_PAG VARCHAR(60),
COM_TOTAL DOUBLE,
COM_CPF VARCHAR(20),
COM_DATA DATE,
COM_VLGARC DOUBLE,
FUNC_ID INT,
CONSTRAINT FK_COMFUN FOREIGN KEY(FUNC_ID) REFERENCES FUNCIONARIOS (FUNC_ID)
);

CREATE TABLE ATENDIMENTOS (
MES_ID INT PRIMARY KEY,
NUM_MESA VARCHAR(4),
QT_PROD INT,
VL_PROD DOUBLE,
PROD_ID INT,
COM_ID INT,
CONSTRAINT FK_ATENPROD FOREIGN KEY(PROD_ID) REFERENCES PRODUTOS (PROD_ID),
CONSTRAINT FK_ATENCOM FOREIGN KEY(COM_ID) REFERENCES COMANDAS (COM_ID)
);


select * from enderecos;
select * from funcionarios;
SELECT END_ID FROM ENDERECOS WHERE END_CEP = 72016180 AND END_NUM = 18;

delete FROM funcionarios where FUNC_ID = 8;
delete FROM enderecos where END_ID = 6;

INSERT INTO FUNCIONARIOS (FUNC_NAME, FUNC_SNAME, FUNC_CPF, FUNC_PASS,FUNC_CARG, FUNC_EMAIL, FUNC_SAL, FUNC_ADMDATE, END_ID)  
VALUES ('administrador','adm',11111111111,'$2y$10$1LaWiNz3mhJylVqLqICAuugfWBcF05vZPrYAULD07sUTE8xR0OuBm','gerente','adm@adm.com.br',1000.00,'2000-01-01',1);

SELECT FUNC_ID, FUNC_NAME, FUNC_CARG, FUNC_CPF, FUNC_EMAIL FROM FUNCIONARIOS;

DESC ATENDIMENTOS;